linters-settings:
  gosec:
    excludes:
    - G108
  lll:
    line-length: 200

  misspell:
    locale: US
  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.16"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive # replacement for golint
    - goconst
    - gofmt
    - goimports
    - unused
    - varcheck
    - deadcode
    - misspell
    - typecheck
    - structcheck
    - staticcheck
    - gosimple
    - gosec
