apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  match:
    - excludedNamespaces: ["staging"]
      processes: ["webhook"]
      # "audit", "sync" for exclusion from audit and opa cache
      # * to include all current and future processes
