apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: assign.mutations.gatekeeper.sh
spec:
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              maxLength: 63